/* Generated by re2c 0.16 */
// Copyright 2011 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "lexer.h"

#include <stdio.h>

#include "eval_env.h"
#include "util.h"

bool Lexer::Error(const string& message, string* err) {
  // Compute line/column.
  int line = 1;
  const char* context = input_.str_;
  for (const char* p = input_.str_; p < last_token_; ++p) {
    if (*p == '\n') {
      ++line;
      context = p + 1;
    }
  }
  int col = last_token_ ? (int)(last_token_ - context) : 0;

  char buf[1024];
  snprintf(buf, sizeof(buf), "%s:%d: ", filename_.AsString().c_str(), line);
  *err = buf;
  *err += message + "\n";

  // Add some context to the message.
  const int kTruncateColumn = 72;
  if (col > 0 && col < kTruncateColumn) {
    int len;
    bool truncated = true;
    for (len = 0; len < kTruncateColumn; ++len) {
      if (context[len] == 0 || context[len] == '\n') {
        truncated = false;
        break;
      }
    }
    *err += string(context, len);
    if (truncated)
      *err += "...";
    *err += "\n";
    *err += string(col, ' ');
    *err += "^ near here";
  }

  return false;
}

Lexer::Lexer(const char* input) {
  Start("input", input);
}

void Lexer::Start(StringPiece filename, StringPiece input) {
  filename_ = filename;
  input_ = input;
  ofs_ = input_.str_;
  last_token_ = NULL;
}

const char* Lexer::TokenName(Token t) {
  switch (t) {
  case ERROR:    return "lexing error";
  case BUILD:    return "'build'";
  case COLON:    return "':'";
  case DEFAULT:  return "'default'";
  case ENDSCOPE: return "'endscope'";
  case EQUALS:   return "'='";
  case IDENT:    return "identifier";
  case INCLUDE:  return "'include'";
  case INDENT:   return "indent";
  case NEWLINE:  return "newline";
  case PIPE2:    return "'||'";
  case PIPE:     return "'|'";
  case POOL:     return "'pool'";
  case RULE:     return "'rule'";
  case SCOPE:    return "'scope'";
  case SUBNINJA: return "'subninja'";
  case TEOF:     return "eof";
  }
  return NULL;  // not reached
}

const char* Lexer::TokenErrorHint(Token expected) {
  switch (expected) {
  case COLON:
    return " ($ also escapes ':')";
  default:
    return "";
  }
}

string Lexer::DescribeLastError() {
  if (last_token_) {
    switch (last_token_[0]) {
    case '\t':
      return "tabs are not allowed, use spaces";
    }
  }
  return "lexing error";
}

void Lexer::UnreadToken() {
  ofs_ = last_token_;
}

Lexer::Token Lexer::ReadToken() {
  const char* p = ofs_;
  const char* q;
  const char* start;
  Lexer::Token token;
  for (;;) {
    start = p;
    
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	static const unsigned char yybm[] = {
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		160, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 192, 192, 128, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 128, 128, 128, 128, 128, 128, 
		128, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 128, 128, 128, 128, 192, 
		128, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
	};
	yych = *p;
	if (yybm[0+yych] & 32) {
		goto yy9;
	}
	if (yych <= '^') {
		if (yych <= ',') {
			if (yych <= '\f') {
				if (yych <= 0x00) goto yy2;
				if (yych == '\n') goto yy6;
				goto yy4;
			} else {
				if (yych <= '\r') goto yy8;
				if (yych == '#') goto yy12;
				goto yy4;
			}
		} else {
			if (yych <= ':') {
				if (yych == '/') goto yy4;
				if (yych <= '9') goto yy13;
				goto yy16;
			} else {
				if (yych <= '=') {
					if (yych <= '<') goto yy4;
					goto yy18;
				} else {
					if (yych <= '@') goto yy4;
					if (yych <= 'Z') goto yy13;
					goto yy4;
				}
			}
		}
	} else {
		if (yych <= 'i') {
			if (yych <= 'b') {
				if (yych == '`') goto yy4;
				if (yych <= 'a') goto yy13;
				goto yy20;
			} else {
				if (yych <= 'd') {
					if (yych <= 'c') goto yy13;
					goto yy21;
				} else {
					if (yych <= 'e') goto yy22;
					if (yych <= 'h') goto yy13;
					goto yy23;
				}
			}
		} else {
			if (yych <= 'r') {
				if (yych == 'p') goto yy24;
				if (yych <= 'q') goto yy13;
				goto yy25;
			} else {
				if (yych <= 'z') {
					if (yych <= 's') goto yy26;
					goto yy13;
				} else {
					if (yych == '|') goto yy27;
					goto yy4;
				}
			}
		}
	}
yy2:
	++p;
	{ token = TEOF;     break; }
yy4:
	++p;
yy5:
	{ token = ERROR;    break; }
yy6:
	++p;
	{ token = NEWLINE;  break; }
yy8:
	yych = *++p;
	if (yych == '\n') goto yy29;
	goto yy5;
yy9:
	yyaccept = 0;
	q = ++p;
	yych = *p;
	if (yybm[0+yych] & 32) {
		goto yy9;
	}
	if (yych <= '\f') {
		if (yych == '\n') goto yy6;
	} else {
		if (yych <= '\r') goto yy31;
		if (yych == '#') goto yy33;
	}
yy11:
	{ token = INDENT;   break; }
yy12:
	yyaccept = 1;
	yych = *(q = ++p);
	if (yych <= 0x00) goto yy5;
	goto yy34;
yy13:
	++p;
	yych = *p;
yy14:
	if (yybm[0+yych] & 64) {
		goto yy13;
	}
	{ token = IDENT;    break; }
yy16:
	++p;
	{ token = COLON;    break; }
yy18:
	++p;
	{ token = EQUALS;   break; }
yy20:
	yych = *++p;
	if (yych == 'u') goto yy37;
	goto yy14;
yy21:
	yych = *++p;
	if (yych == 'e') goto yy38;
	goto yy14;
yy22:
	yych = *++p;
	if (yych == 'n') goto yy39;
	goto yy14;
yy23:
	yych = *++p;
	if (yych == 'n') goto yy40;
	goto yy14;
yy24:
	yych = *++p;
	if (yych == 'o') goto yy41;
	goto yy14;
yy25:
	yych = *++p;
	if (yych == 'u') goto yy42;
	goto yy14;
yy26:
	yych = *++p;
	if (yych == 'c') goto yy43;
	if (yych == 'u') goto yy44;
	goto yy14;
yy27:
	++p;
	if ((yych = *p) == '|') goto yy45;
	{ token = PIPE;     break; }
yy29:
	++p;
	{ token = NEWLINE;  break; }
yy31:
	yych = *++p;
	if (yych == '\n') goto yy29;
yy32:
	p = q;
	if (yyaccept == 0) {
		goto yy11;
	} else {
		goto yy5;
	}
yy33:
	++p;
	yych = *p;
yy34:
	if (yybm[0+yych] & 128) {
		goto yy33;
	}
	if (yych <= 0x00) goto yy32;
	++p;
	{ continue; }
yy37:
	yych = *++p;
	if (yych == 'i') goto yy47;
	goto yy14;
yy38:
	yych = *++p;
	if (yych == 'f') goto yy48;
	goto yy14;
yy39:
	yych = *++p;
	if (yych == 'd') goto yy49;
	goto yy14;
yy40:
	yych = *++p;
	if (yych == 'c') goto yy50;
	goto yy14;
yy41:
	yych = *++p;
	if (yych == 'o') goto yy51;
	goto yy14;
yy42:
	yych = *++p;
	if (yych == 'l') goto yy52;
	goto yy14;
yy43:
	yych = *++p;
	if (yych == 'o') goto yy53;
	goto yy14;
yy44:
	yych = *++p;
	if (yych == 'b') goto yy54;
	goto yy14;
yy45:
	++p;
	{ token = PIPE2;    break; }
yy47:
	yych = *++p;
	if (yych == 'l') goto yy55;
	goto yy14;
yy48:
	yych = *++p;
	if (yych == 'a') goto yy56;
	goto yy14;
yy49:
	yych = *++p;
	if (yych == 's') goto yy57;
	goto yy14;
yy50:
	yych = *++p;
	if (yych == 'l') goto yy58;
	goto yy14;
yy51:
	yych = *++p;
	if (yych == 'l') goto yy59;
	goto yy14;
yy52:
	yych = *++p;
	if (yych == 'e') goto yy61;
	goto yy14;
yy53:
	yych = *++p;
	if (yych == 'p') goto yy63;
	goto yy14;
yy54:
	yych = *++p;
	if (yych == 'n') goto yy64;
	goto yy14;
yy55:
	yych = *++p;
	if (yych == 'd') goto yy65;
	goto yy14;
yy56:
	yych = *++p;
	if (yych == 'u') goto yy67;
	goto yy14;
yy57:
	yych = *++p;
	if (yych == 'c') goto yy68;
	goto yy14;
yy58:
	yych = *++p;
	if (yych == 'u') goto yy69;
	goto yy14;
yy59:
	++p;
	if (yybm[0+(yych = *p)] & 64) {
		goto yy13;
	}
	{ token = POOL;     break; }
yy61:
	++p;
	if (yybm[0+(yych = *p)] & 64) {
		goto yy13;
	}
	{ token = RULE;     break; }
yy63:
	yych = *++p;
	if (yych == 'e') goto yy70;
	goto yy14;
yy64:
	yych = *++p;
	if (yych == 'i') goto yy72;
	goto yy14;
yy65:
	++p;
	if (yybm[0+(yych = *p)] & 64) {
		goto yy13;
	}
	{ token = BUILD;    break; }
yy67:
	yych = *++p;
	if (yych == 'l') goto yy73;
	goto yy14;
yy68:
	yych = *++p;
	if (yych == 'o') goto yy74;
	goto yy14;
yy69:
	yych = *++p;
	if (yych == 'd') goto yy75;
	goto yy14;
yy70:
	++p;
	if (yybm[0+(yych = *p)] & 64) {
		goto yy13;
	}
	{ token = SCOPE;    break; }
yy72:
	yych = *++p;
	if (yych == 'n') goto yy76;
	goto yy14;
yy73:
	yych = *++p;
	if (yych == 't') goto yy77;
	goto yy14;
yy74:
	yych = *++p;
	if (yych == 'p') goto yy79;
	goto yy14;
yy75:
	yych = *++p;
	if (yych == 'e') goto yy80;
	goto yy14;
yy76:
	yych = *++p;
	if (yych == 'j') goto yy82;
	goto yy14;
yy77:
	++p;
	if (yybm[0+(yych = *p)] & 64) {
		goto yy13;
	}
	{ token = DEFAULT;  break; }
yy79:
	yych = *++p;
	if (yych == 'e') goto yy83;
	goto yy14;
yy80:
	++p;
	if (yybm[0+(yych = *p)] & 64) {
		goto yy13;
	}
	{ token = INCLUDE;  break; }
yy82:
	yych = *++p;
	if (yych == 'a') goto yy85;
	goto yy14;
yy83:
	++p;
	if (yybm[0+(yych = *p)] & 64) {
		goto yy13;
	}
	{ token = ENDSCOPE; break; }
yy85:
	++p;
	if (yybm[0+(yych = *p)] & 64) {
		goto yy13;
	}
	{ token = SUBNINJA; break; }
}

  }

  last_token_ = start;
  ofs_ = p;
  if (token != NEWLINE && token != TEOF)
    EatWhitespace();
  return token;
}

bool Lexer::PeekToken(Token token) {
  Token t = ReadToken();
  if (t == token)
    return true;
  UnreadToken();
  return false;
}

void Lexer::EatWhitespace() {
  const char* p = ofs_;
  const char* q;
  for (;;) {
    ofs_ = p;
    
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	yych = *p;
	if (yybm[0+yych] & 128) {
		goto yy93;
	}
	if (yych <= 0x00) goto yy89;
	if (yych == '$') goto yy96;
	goto yy91;
yy89:
	++p;
	{ break; }
yy91:
	++p;
yy92:
	{ break; }
yy93:
	++p;
	yych = *p;
	if (yybm[0+yych] & 128) {
		goto yy93;
	}
	{ continue; }
yy96:
	yych = *(q = ++p);
	if (yych == '\n') goto yy97;
	if (yych == '\r') goto yy99;
	goto yy92;
yy97:
	++p;
	{ continue; }
yy99:
	yych = *++p;
	if (yych == '\n') goto yy101;
	p = q;
	goto yy92;
yy101:
	++p;
	{ continue; }
}

  }
}

bool Lexer::ReadIdent(string* out) {
  const char* p = ofs_;
  for (;;) {
    const char* start = p;
    
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0, 128, 128,   0, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0,   0,   0,   0,   0,   0, 
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128,   0,   0,   0,   0, 128, 
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	yych = *p;
	if (yybm[0+yych] & 128) {
		goto yy107;
	}
	++p;
	{ return false; }
yy107:
	++p;
	yych = *p;
	if (yybm[0+yych] & 128) {
		goto yy107;
	}
	{
      out->assign(start, p - start);
      break;
    }
}

  }
  ofs_ = p;
  EatWhitespace();
  return true;
}

bool Lexer::ReadEvalString(EvalString* eval, bool path, string* err) {
  const char* p = ofs_;
  const char* q;
  const char* start;
  for (;;) {
    start = p;
    
{
	unsigned char yych;
	static const unsigned char yybm[] = {
		  0,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,   0,  16,  16,   0,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 32,  16,  16,  16,   0,  16,  16,  16, 
		 16,  16,  16,  16,  16, 208, 144,  16, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208,   0,  16,  16,  16,  16,  16, 
		 16, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208,  16,  16,  16,  16, 208, 
		 16, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208, 208, 208, 208, 208, 208, 
		208, 208, 208,  16,   0,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
		 16,  16,  16,  16,  16,  16,  16,  16, 
	};
	yych = *p;
	if (yybm[0+yych] & 16) {
		goto yy114;
	}
	if (yych <= '\r') {
		if (yych <= 0x00) goto yy112;
		if (yych <= '\n') goto yy117;
		goto yy119;
	} else {
		if (yych <= ' ') goto yy117;
		if (yych <= '$') goto yy121;
		goto yy117;
	}
yy112:
	++p;
	{
      last_token_ = start;
      return Error("unexpected EOF", err);
    }
yy114:
	++p;
	yych = *p;
	if (yybm[0+yych] & 16) {
		goto yy114;
	}
	{
      eval->AddText(StringPiece(start, p - start));
      continue;
    }
yy117:
	++p;
	{
      if (path) {
        p = start;
        break;
      } else {
        if (*start == '\n')
          break;
        eval->AddText(StringPiece(start, 1));
        continue;
      }
    }
yy119:
	++p;
	if ((yych = *p) == '\n') goto yy122;
	{
      last_token_ = start;
      return Error(DescribeLastError(), err);
    }
yy121:
	yych = *++p;
	if (yybm[0+yych] & 64) {
		goto yy134;
	}
	if (yych <= ' ') {
		if (yych <= '\f') {
			if (yych == '\n') goto yy126;
			goto yy124;
		} else {
			if (yych <= '\r') goto yy129;
			if (yych <= 0x1F) goto yy124;
			goto yy130;
		}
	} else {
		if (yych <= '/') {
			if (yych == '$') goto yy132;
			goto yy124;
		} else {
			if (yych <= ':') goto yy137;
			if (yych <= '`') goto yy124;
			if (yych <= '{') goto yy139;
			goto yy124;
		}
	}
yy122:
	++p;
	{
      if (path)
        p = start;
      break;
    }
yy124:
	++p;
yy125:
	{
      last_token_ = start;
      return Error("bad $-escape (literal $ must be written as $$)", err);
    }
yy126:
	++p;
	yych = *p;
	if (yybm[0+yych] & 32) {
		goto yy126;
	}
	{
      continue;
    }
yy129:
	yych = *++p;
	if (yych == '\n') goto yy140;
	goto yy125;
yy130:
	++p;
	{
      eval->AddText(StringPiece(" ", 1));
      continue;
    }
yy132:
	++p;
	{
      eval->AddText(StringPiece("$", 1));
      continue;
    }
yy134:
	++p;
	yych = *p;
	if (yybm[0+yych] & 64) {
		goto yy134;
	}
	{
      eval->AddSpecial(StringPiece(start + 1, p - start - 1));
      continue;
    }
yy137:
	++p;
	{
      eval->AddText(StringPiece(":", 1));
      continue;
    }
yy139:
	yych = *(q = ++p);
	if (yybm[0+yych] & 128) {
		goto yy143;
	}
	goto yy125;
yy140:
	++p;
	yych = *p;
	if (yych == ' ') goto yy140;
	{
      continue;
    }
yy143:
	++p;
	yych = *p;
	if (yybm[0+yych] & 128) {
		goto yy143;
	}
	if (yych == '}') goto yy146;
	p = q;
	goto yy125;
yy146:
	++p;
	{
      eval->AddSpecial(StringPiece(start + 2, p - start - 3));
      continue;
    }
}

  }
  last_token_ = start;
  ofs_ = p;
  if (path)
    EatWhitespace();
  // Non-path strings end in newlines, so there's no whitespace to eat.
  return true;
}
